### PR TITLE
Require Space in Lambda's

### PR DESCRIPTION
**Pull request by onesneakymofo**
2018-08-16 at 1 43 pm

I want this. Can we have it?

### CODE REVIEW

**Comment by tmiller** [comment]
I was all for it at first, but now I am torn.

**Comment by afomera** [comment]
Personally I prefer it _without_ spaces

**Review by tmiller — APPROVED** [review]

**Review by licatajustin — APPROVED** [review]

**Comment by afomera** [comment]
I'm so sad :(

**Comment by onesneakymofo** [comment]
it ok bb

**Pull request merged**
